name: Channel Poster
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [thirteen]
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  poster:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install necessary dependencies for the script to work
      - name: Install Dep
        run: sudo pip install pyTelegramBotAPI
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: thirteen

      - name: Github config
        run: |
          git config --global user.name "Darkstar085"
          git config --global user.email "sipunkumar85@gmail.com"

      # Post the update
      - name: Bot
        run: sudo -E python3 .github/scripts/post.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT: ${{ secrets.CHAT_ID }}

      - name: debug
        run: sudo ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: releases
          retention-days: 2
          path: |
            release_notes.txt
            urls.txt
            tag.txt

      # Commit the changes and push to git
      - name: Commit and Push Changes
        run: sudo bash .github/scripts/push.sh

  release:
    runs-on: ubuntu-latest
    needs: poster
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: thirteen

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: releases

      - name: debug
        run: sudo ls

      - name: Download
        run: sudo -E python3 .github/scripts/download.py

      - name: Release to GH Releases
        run: sudo -E bash .github/scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
